### ISSUE TITLE
Parcel

### ISSUE THREAD

**Issue by igorkamyshev** [nyancss/nyancss#21]
Hello! Great lib, thanks for it. I want use it with Parcel, could you explain, how I can do it?

**Comment by kossnocorp** [comment]
You're welcome!

Here's how it works. First of all, Nyan CSS depends on CSS Modules output that generates an object that looks like that:

```js
{
  'Button-color-red': 'Button-color-red-1ca66',
  'Button-color-green': 'Button-color-green-1ca66'
}
```

[nyancss-css-modules](https://github.com/nyancss/nyancss-css-modules) takes that object and converts it to [NyanCSSMap](https://github.com/nyancss/nyancss-types/blob/master/src/index.ts#L25). Then the map is converted to components using one of the adaptors:

- [React/Preact](https://github.com/nyancss/nyancss-react)
- [Vue.js](https://github.com/nyancss/nyancss-vue)
- [Class names](https://github.com/nyancss/nyancss-class-names)

Here's how the full process looks for webpack + React: https://github.com/nyancss/nyancss-css-modules-loader/blob/master/src/react/index.

I'm sure it's a lot to process at once (and also explain), so feel free to ask questions. You can also ping me at Telegram: https://t.me/kossnocorp

**Comment by igorkamyshev** [comment]
Thanks! I will try to do it in October/November. 🤓

**Comment by kossnocorp** [comment]
@igorkamyshev fantastic, thank you! Ping me if you need any help.
